name: SickChill Docker Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3.0.1
      - name: setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
        with:
         platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.4.0
        with:
         version: latest
      - name: login to docker hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      - name: build the docker image
        run: |
          BDATE=$(date +%d-%m-%Y) && docker buildx build --push \
          --tag avpnusr/sickchill:latest --tag avpnusr/sickchill:$BDATE \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --file ./Dockerfile .
